# Generated by Django 4.1.2 on 2022-10-31 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferretic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventas',
            old_name='empleado',
            new_name='nombre_empleado',
        ),
    ]
