# Generated by Django 4.1.2 on 2022-10-31 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferretic', '0002_rename_empleado_ventas_nombre_empleado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compras',
            old_name='empleado',
            new_name='nombre_empleado',
        ),
    ]
