# Generated by Django 4.1.2 on 2022-10-31 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferretic', '0003_rename_empleado_compras_nombre_empleado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ventas',
            new_name='Venta',
        ),
    ]
