# Generated by Django 4.1.2 on 2022-11-02 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferretic', '0004_rename_ventas_venta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre_cliente',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='compras',
            old_name='nombre_empleado',
            new_name='empleado',
        ),
        migrations.RenameField(
            model_name='compras',
            old_name='nombre_producto',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='compras',
            old_name='nombre_proveedor',
            new_name='proveedor',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='nombre_empleado',
            new_name='empleado',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre_producto',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='nombre_proveedor',
            new_name='proveedor',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='nombre_cliente',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='nombre_empleado',
            new_name='empleado',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='nombre_producto',
            new_name='producto',
        ),
    ]
