# Generated by Django 4.1.2 on 2022-11-02 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferretic', '0005_rename_nombre_cliente_cliente_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compras',
            old_name='fecha_venta',
            new_name='fecha_compra',
        ),
    ]
