# Generated by Django 4.1.2 on 2022-11-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferretic', '0006_rename_fecha_venta_compras_fecha_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
