# Generated by Django 4.1.2 on 2022-11-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferretic', '0009_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='token',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
