# Generated by Django 6.0 on 2026-01-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferretic', '0010_alter_usuario_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
